import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtempSync,mkdirSync,copyFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,dirname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {once} from 'node:events';
import http from 'node:http';
test('library persistence, publication boundaries, upload versions and request security',async t=>{
 const base=join(dirname(fileURLToPath(import.meta.url)),'..');const root=mkdtempSync(join(tmpdir(),'linban-test-'));mkdirSync(join(root,'data'));copyFileSync(join(base,'data','seed.json'),join(root,'data','seed.json'));
 const child=spawn(process.execPath,[join(base,'server.mjs')],{env:{...process.env,LIBRARY_ROOT:root,PORT:'0'},stdio:['ignore','pipe','pipe']});
 t.after(async()=>{child.kill();await once(child,'exit').catch(()=>{});rmSync(root,{recursive:true,force:true});});
 const url=await new Promise((resolve,reject)=>{let s='';child.stdout.on('data',c=>{s+=c;const match=/LIBRARY_READY (http:\/\/127\.0\.0\.1:\d+)/.exec(s);if(match)resolve(match[1]);});child.on('error',reject);child.once('exit',code=>reject(new Error('server exited '+code)));});
 const get=path=>fetch(url+path);const initial=await(await get('/api/catalog')).json();assert.equal(initial.items.length,28);assert.equal(initial.categories.length,14);
 const session=await(await get('/api/admin/session')).json();const headers={'Content-Type':'application/json','Origin':url,'X-Library-Token':session.token};
 let r=await fetch(url+'/api/admin/items',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:'evil'})});assert.equal(r.status,403);
 r=await fetch(url+'/api/admin/items',{method:'POST',headers:{...headers,Origin:'https://untrusted.example'},body:JSON.stringify({title:'evil'})});assert.equal(r.status,403);
 const hostileHostStatus=await new Promise((resolve,reject)=>{const req=http.get(url+'/api/catalog',{headers:{Host:'attacker.example'}},res=>{res.resume();resolve(res.statusCode);});req.on('error',reject);});assert.equal(hostileHostStatus,403);
 const post=body=>fetch(url+'/api/admin/items',{method:'POST',headers,body:JSON.stringify(body)});
 r=await post({title:'测试书目',status:'draft',proton_url:'javascript:alert(1)'});assert.equal(r.status,400);
 r=await post({title:'测试书目',status:'draft',format:'TXT'});assert.equal(r.status,200);const item=await r.json();assert.equal(item.revision,1);
 assert.ok(!(await(await get('/api/catalog')).json()).items.some(i=>i.id===item.id));
 const upload=()=>fetch(url+'/api/admin/upload?id='+item.id+'&name='+encodeURIComponent('测试.txt'),{method:'POST',headers:{Origin:url,'X-Library-Token':session.token,'Content-Type':'application/octet-stream'},body:'hello archive'});
 r=await upload();assert.equal(r.status,201);const file=await r.json();assert.equal(file.sha256.length,64);
 r=await get('/files/'+file.id);assert.equal(r.status,404);
 r=await upload();assert.equal(r.status,200);assert.equal((await r.json()).duplicate,true);
 await post({id:item.id,title:'已发布测试书目',status:'published'});
 assert.ok((await(await get('/api/catalog')).json()).items.some(i=>i.id===item.id));
 r=await get('/files/'+file.id);assert.equal(await r.text(),'hello archive');
 r=await fetch(url+'/files/'+file.id,{headers:{Range:'bytes=0-4'}});assert.equal(r.status,206);assert.equal(await r.text(),'hello');
 r=await fetch(url+'/files/'+file.id,{headers:{Range:'bytes=999-1000'}});assert.equal(r.status,416);
 const history=await(await get('/api/admin/history?id='+item.id)).json();assert.equal(history.length,3);assert.equal(JSON.parse(history[2].snapshot).title,'测试书目');
 const sync=await(await get('/api/admin/sync')).json();assert.equal(sync.connected,false);assert.equal(sync.jobs[0].state,'not_connected');
 await post({id:item.id,status:'archived'});assert.equal((await get('/files/'+file.id)).status,404);
 assert.equal((await get('/data/library.sqlite')).status,404);
 assert.equal((await get('/admin')).status,200);
});
